<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Raymonds-MacBook-Pro.local" failures="1" tests="1" name="TestRunner" time="4.831" errors="0" timestamp="2024-02-18T12:40:49 EST" skipped="0">
  <testcase classname="TestRunner" name="runScenario" time="4.831">
    <failure message="expected [] but found [Success!]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [] but found [Success!]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at stepDef.signup_step.studentShouldSuccessfullyCreateTheirAccount(signup_step.java:88)
at âœ½.student should successfully create their account(file:///Users/raymondmurad/Documents/TalentTEK/Cucumber_FW/src/test/java/features/signup.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- TestRunner -->
